set -s escape-time 5
set -g allow-passthrough on
set -g visual-activity off
set -g status-left-length 25
set -ga terminal-overrides ',xterm*:Tc:smxx=\E[9m'

setw -g mode-keys vi

set-option -g status-position bottom
set-option -g set-clipboard on

bind -n M-s display-popup -E -w 80% -h 70% "tv sesh"
bind -n M-k display-popup -d "#{pane_current_path}" -w 85% -h 85% -E "nnn -P p"


# Previous/next window inside current session
bind -n M-n previous-window
bind -n M-o next-window


# Visible session cycling
bind -n M-c run-shell "~/.tmux/scripts/next-session"
bind -n M-C run-shell "~/.tmux/scripts/prev-session"

bind -n M-m if-shell '[ "#{session_name}" = "_monitor" ]' \
    'switch-client -l' \
    'if-shell "tmux has-session -t _monitor 2>/dev/null" "switch-client -t _monitor"'

bind -n M-d if-shell '[ "#{session_name}" = "_services" ]' \
    'switch-client -l' \
    'if-shell "tmux has-session -t _services 2>/dev/null" "switch-client -t _services"'

bind -n M-y if-shell '[ "#{session_name}" = "_fs" ]' \
    'switch-client -l' \
    'switch-client -t _fs'

# All sessions
bind -n M-a choose-tree -sZ

# Copy mode
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# Prevent accidental session kills
bind X confirm-before -p "Kill session #S? (y/n)" kill-session

# Start `_services`
if-shell 'tmux has-session -t _services 2>/dev/null' '' \
    'new-session -d -s _services'

# start `yazi`
if-shell 'tmux has-session -t _fs 2>/dev/null' '' \
    'new-session -d -s _fs "yazi"'

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'vaaleyard/tmux-dotbar'

set -g @tmux-dotbar-bg "#1c0c28"
set -g @tmux-dotbar-fg-current "#ffffff"

if-shell '[ -n "$SSH_CONNECTION" ]' \
  "set -g @tmux-dotbar-fg-session '#ff6666'" \
  "set -g @tmux-dotbar-fg-session '#c6e960'"

run '~/.tmux/plugins/tpm/tpm'
