if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Path and Environment Variables
export PATH="$HOME/.cargo/bin:$PATH"
export PATH="$HOME/.local/bin:$PATH"

# Aliases
alias v="nvim"
alias lg="lazygit"
alias datalogtool="$HOME/Luftronix-daily/ubuntu/DataLogTool"
alias mltunnels="$HOME/Scripts/ml-tunnels.sh"

# Custom Functions
function sesh-sessions() {
  {
    exec </dev/tty
    exec <&1
    local session

    session=$(tv sesh > /dev/tty)

    zle reset-prompt > /dev/null 2>&1 || true
    [[ -z "$session" ]] && return
    sesh connect $session
  }
}

# External Tool Initializations
eval "$(oh-my-posh init zsh --config "${XDG_CONFIG_HOME:-$HOME/.config}/oh-my-posh.toml")"
eval "$(zoxide init --cmd cd zsh)"
eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
fpath+=${ZDOTDIR:-~}/.zsh_functions

# History Substring Search Keybindings
for keymap in emacs viins; do
  bindkey -M $keymap '^[[A' history-substring-search-up
  bindkey -M $keymap '^[[B' history-substring-search-down
  bindkey -M $keymap '^[OA' history-substring-search-up
  bindkey -M $keymap '^[OB' history-substring-search-down
done
unset keymap

export EDITOR="nvim"
export VISUAL="nvim"

autoload -U edit-command-line
zle -N edit-command-line
zle -N sesh-sessions

bindkey -M emacs '\es' sesh-sessions
bindkey -M vicmd '\es' sesh-sessions
bindkey -M viins '\es' sesh-sessions
bindkey -M emacs '^Xe' edit-command-line
bindkey -M viins '^Xe' edit-command-line
bindkey -M vicmd 'v'   edit-command-line

