[save]
autosave = "after_delay"
format_on_save = false
autosave_delay = 1000

[mcp]
presets = []

[mcp.mcpServers]

[runtime]
watcher_on_save = "lazy"
default_sql_output = "auto"
on_cell_change = "autorun"
dotenv = []
default_auto_download = []
reactive_tests = true
auto_instantiate = true
auto_reload = "off"
std_stream_max_bytes = 1000000
output_max_bytes = 8000000

[diagnostics]

[package_management]
manager = "uv"

[snippets]
custom_paths = []
include_default_snippets = true

[completion]
copilot = false
activate_on_typing = true

[ai]
inline_tooltip = false
rules = ""
mode = "manual"

[ai.models]
displayed_models = []
custom_models = []

[keymap]
destructive_delete = true
preset = "vim"
vimrc = "/home/artur/marimo.vimrc"

[keymap.overrides]
"command.pasteCell" = "Alt-v"
"command.copyCell" = "Alt-c"

[formatting]
line_length = 79

[server]
browser = "default"
follow_symlink = false

[language_servers.basedpyright]
enabled = true

[language_servers.ty]

[language_servers.pylsp]
enable_flake8 = false
enable_pyflakes = false
enable_mypy = true
enabled = true
enable_pydocstyle = false
enable_ruff = true
enable_pylint = false

[display]
theme = "dark"
default_table_page_size = 10
dataframes = "rich"
code_editor_font_size = 18
cell_output = "below"
reference_highlighting = false
default_table_max_columns = 50
default_width = "full"

[experimental]
